---
#buid project
#- name: build app
#shell: ng build --configuration=production
 
# tasks file for buildDocker
#- name: install npm
#  apt: name=npm
#- name: running npm install
#  shell: npm install /var/lib/jenkins/workspace/buildFront
#- name: build app
#  shell: ng build --prod
- name: create image docker
  docker_image:
    name: pfe2020
    build:
     path: /var/lib/jenkins/workspace/buildFront
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: myapp_container
    image: pfe2020:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
- name: log into docker hub registry
  docker_login:
    email: "aminelimem14@gmail.com"
    username: "aminelimem"
    password: "Bonjour.1234"
- name: Tag and push to docker hub
  docker_image:
    name: pfe2020:latest
    repository: aminelimem/pfe2020
    push: yes
    source: local
       
        
